In [7]:
import numpy as np

a = np.array([[1, 2, 3],[7, 8, 9]]) # 2D array
b = np.array([4, 5, 6]) 
c = a + b # sum
print(c)
c = a ** b # pow
print(c)
c = a * b # product
print(c)
c = a / b # division
print(c)


[[ 5  7  9]
 [11 13 15]]
[[     1     32    729]
 [  2401  32768 531441]]
[[ 4 10 18]
 [28 40 54]]
[[0.25 0.4  0.5 ]
 [1.75 1.6  1.5 ]]


In [11]:
array = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])

#average
average = np.average(array, axis=0) #average of each column
print(average)
average = np.average(array, axis=1) #average of each row
print(average)
#mean
mean = np.mean(array)
print(mean)
#median
median = np.median(array)
print(median)
#std
std = np.std(array)
print(std)
#variance
variance = np.var(array)
print(variance)


[4. 5. 6.]
[2. 5. 8.]
5.0
5.0
2.581988897471611
6.666666666666667


In [15]:
#string manipulation
x = np.array(['a', 'b', 'cc'])
y = np.array(['d', 'b', 'f'])
z = np.char.add(x, y) #concatenate
print(z)
z= np.char.multiply(x, 3) #repeat
print(z)
#string comparison
z = np.char.equal(x, y) #compare
print(z)
#string length
z = np.char.str_len(x) #length
print(z)
#string split
z = np.char.split(x) #split
print(z)
#string join
z = np.char.join('-', x) #join
print(z)
#string replace
z = np.char.replace(x, 'a', 'A') #replace
print(z)
z= np.char.strip(x) #strip
print(z)
#string upper and lower
z = np.char.upper(x) #upper
print(z)
z = np.char.lower(x) #lower
print(z)
#string capitalize
z = np.char.capitalize(x) #capitalize
print(z)

['ad' 'bb' 'ccf']
['aaa' 'bbb' 'cccccc']
[False  True False]
[1 1 2]
[list(['a']) list(['b']) list(['cc'])]
['a' 'b' 'c-c']
['A' 'b' 'cc']
['a' 'b' 'cc']
['A' 'B' 'CC']
['a' 'b' 'cc']
['A' 'B' 'Cc']


In [16]:
#indexing and slicing
a = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print(a[0, 0]) #first element
print(a[0, 1]) #second element
print(a[1, 0]) #fourth element
print(a[1, 1]) #fifth element
#negative indexing
print(a[-1, -1]) #last element
print(a[-1, -2]) #second last element
#SLICING
print(a[0:2, 0:2]) #first two rows and first two columns
print(a[1:3, 1:3]) #last two rows and last two columns


1
2
4
5
9
8
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
