In [3]:
#calculate determinate of a matrix
#implement a function
#that takes a matrix as input and returns its determinant
#use recursion to calculate the determinant of a matrix
#the determinant of a 2x2 matrix is ad-bc
#the determinant of a 3x3 matrix is a(ei-fh)-b(di-fg)+c(dh-eg)
#the determinant of a 4x4 matrix is a(ei-fh)-b(di-fg)+c(dh-eg)+d(ef-gh)

def determinant(matrix):
    #base case for 2x2 matrix
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    #base case for 3x3 matrix
    elif len(matrix) == 3:
        return (matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) -
                matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0]) +
                matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0]))
    #recursive case for larger matrices
    else:
        det = 0
        for c in range(len(matrix)):
            det += ((-1) ** c) * matrix[0][c] * determinant([row[:c] + row[c+1:] for row in matrix[1:]])
        return det

matrix_2x2 = [[1, 2], [3, 4]]
matrix_3x3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_4x4 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
print("Determinant of 2x2 matrix:", determinant(matrix_2x2)) # -2
print("Determinant of 3x3 matrix:", determinant(matrix_3x3)) # 0
print("Determinant of 4x4 matrix:", determinant(matrix_4x4)) # 0
print("Determinant of 1x1 matrix:", determinant([[5]])) # 5
print("Determinant of 5x5 matrix:", determinant([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])) #0



Determinant of 2x2 matrix: -2
Determinant of 3x3 matrix: 0
Determinant of 4x4 matrix: 0
Determinant of 1x1 matrix: 0
Determinant of 5x5 matrix: 0


In [ ]:
import numpy as np

#add matirx using numpy
matrixA = np.array([[1, 2], 
                    [3, 4]])
matrixB = np.array([[5, 6],
                    [7, 8]])
matrixC = np.add(matrixA, matrixB)
print("Matrix A + Matrix B =\n", matrixC)
#multiply matrix using numpy
matrixA = np.array([[1, 2], 
                    [3, 4]])
matrixB = np.array([[5, 6], 
                    [7, 8]])
matrixC = np.multiply(matrixA, matrixB)
print("Matrix A * Matrix B =\n", matrixC)
#transpose matrix using numpy
matrixA = np.array([[1, 2], [3, 4]])
matrixB = np.transpose(matrixA)
print("Transpose of Matrix A =\n", matrixB)
#inverse matrix using numpy
matrixA = np.array([[1, 2], [3, 4]])
matrixB = np.linalg.inv(matrixA)
print("Inverse of Matrix A =\n", matrixB)
#determinant of matrix using numpy
matrixA = np.array([[1, 2], [3, 4]])
det = np.linalg.det(matrixA)
print("Determinant of Matrix A =\n", det)
#eigenvalues and eigenvectors of matrix using numpy
matrixA = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrixA)
print("Eigenvalues of Matrix A =\n", eigenvalues)
print("Eigenvectors of Matrix A =\n", eigenvectors)


Matrix A + Matrix B =
 [[ 6  8]
 [10 12]]
Matrix A * Matrix B =
 [[ 5 12]
 [21 32]]
Transpose of Matrix A =
 [[1 3]
 [2 4]]
Inverse of Matrix A =
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of Matrix A =
 -2.0000000000000004
Eigenvalues of Matrix A =
 [-0.37228132  5.37228132]
Eigenvectors of Matrix A =
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
matrixA = np.array([[1, 2], 
                    [3, 4]])
matrixB = np.array([[5, 6], 
                    [7, 8]])

#cross product of two matrices using numpy using operator @
matrixA @ matrixB

array([[19, 22],
       [43, 50]])