In [54]:
import random
import numpy as np
#indexing the lazy way
def rnd_idx(shape,negative=False):
    """Generate random indices for a given shape."""
    if negative:
        return tuple(random.randrange(s)-s for s in shape)
    else:
        return tuple(random.randrange(s) for s in shape)
def rnd_idx_gen(shape,negative=False):
    """Generate random indices for a given shape."""
    used = set()
    while len(used) < np.prod(shape):
        idx = rnd_idx(shape,negative)
        if idx not in used:
            used.add(idx)
            yield idx
# generate 1d,2d,3d arrays
arr = np.array([1, 2, 3,4,5,6,7,8,9,10,11,12])
a = arr.reshape(12)
b = arr.reshape(3,4)
c = arr.reshape(2,2,3)


In [55]:
#positive indexing
print("positive indexing")
list(map(lambda loc: print(f"elem at {loc}: {a[loc]}"), rnd_idx_gen(a.shape)))
print("===")
list(map(lambda loc: print(f"elem at {loc}: {b[loc]}"), rnd_idx_gen(b.shape)))
print("===")
list(map(lambda loc: print(f"elem at {loc}: {c[loc]}"), rnd_idx_gen(c.shape)))
print("======")

positive indexing
elem at (7,): 8
elem at (5,): 6
elem at (0,): 1
elem at (3,): 4
elem at (11,): 12
elem at (9,): 10
elem at (8,): 9
elem at (4,): 5
elem at (6,): 7
elem at (10,): 11
elem at (1,): 2
elem at (2,): 3
===
elem at (0, 0): 1
elem at (0, 2): 3
elem at (1, 2): 7
elem at (2, 2): 11
elem at (0, 3): 4
elem at (2, 0): 9
elem at (1, 1): 6
elem at (2, 1): 10
elem at (1, 3): 8
elem at (0, 1): 2
elem at (2, 3): 12
elem at (1, 0): 5
===
elem at (1, 1, 2): 12
elem at (1, 1, 0): 10
elem at (0, 1, 0): 4
elem at (1, 0, 1): 8
elem at (0, 0, 1): 2
elem at (1, 1, 1): 11
elem at (1, 0, 2): 9
elem at (1, 0, 0): 7
elem at (0, 1, 2): 6
elem at (0, 1, 1): 5
elem at (0, 0, 0): 1
elem at (0, 0, 2): 3


In [56]:
##negative indexing the lazy way
print("negative indexing")
list(map(lambda loc: print(f"elem at {loc}: {a[loc]}"), rnd_idx_gen(a.shape,negative=True)))
print("===")
list(map(lambda loc: print(f"elem at {loc}: {b[loc]}"), rnd_idx_gen(b.shape,negative=True)))
print("===")
list(map(lambda loc: print(f"elem at {loc}: {c[loc]}"), rnd_idx_gen(c.shape,negative=True)))
print("======")

negative indexing
elem at (-10,): 3
elem at (-11,): 2
elem at (-5,): 8
elem at (-8,): 5
elem at (-4,): 9
elem at (-6,): 7
elem at (-12,): 1
elem at (-3,): 10
elem at (-7,): 6
elem at (-1,): 12
elem at (-2,): 11
elem at (-9,): 4
===
elem at (-2, -2): 7
elem at (-1, -2): 11
elem at (-1, -1): 12
elem at (-3, -4): 1
elem at (-2, -1): 8
elem at (-3, -2): 3
elem at (-1, -4): 9
elem at (-1, -3): 10
elem at (-2, -4): 5
elem at (-3, -1): 4
elem at (-3, -3): 2
elem at (-2, -3): 6
===
elem at (-2, -2, -3): 1
elem at (-1, -2, -3): 7
elem at (-2, -2, -1): 3
elem at (-1, -2, -2): 8
elem at (-1, -1, -3): 10
elem at (-2, -1, -3): 4
elem at (-2, -2, -2): 2
elem at (-1, -1, -2): 11
elem at (-2, -1, -1): 6
elem at (-1, -2, -1): 9
elem at (-2, -1, -2): 5
elem at (-1, -1, -1): 12


In [57]:
#slicing
print("slicing")
print(a[3:4])
print(a[3:4].shape)
print(b[1:2])
print(b[1:2].shape)
print(b[0:2,0:2])
print(b[0:2,0:2].shape)

print("======")

slicing
[4]
(1,)
[[5 6 7 8]]
(1, 4)
[[1 2]
 [5 6]]
(2, 2)


In [39]:
print(a)
print(a[0:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3]


In [48]:
print(a[-1])
print(a[-12])

12
1
