In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)
print(arr.itemsize) 
print(arr.T)
print(arr.T.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
5
1
4
[1 2 3 4 5]
(5,)


In [30]:
def print_array(arr, type=0):
    if type == 0:
        print(f"Array: {arr}, size: {arr.size}, itemsize: {arr.itemsize}, shape: {arr.shape}, ndim: {arr.ndim}")
    elif type == 1:
        print(f"dtype: {arr.dtype}, size: {arr.size}, itemsize: {arr.itemsize}, shape: {arr.shape}, ndim: {arr.ndim}")
    elif type == 2:
        print(f"shape: {arr.shape}, ndim: {arr.ndim}")    

In [ ]:
arr0 = np.array(24)
print_array(arr0)
arr0 = np.array([1,3,5])
print_array(arr0)
arr0 = np.array([[1],[3],[5]])
print_array(arr0)
arr0 = np.array([[[1],[3],[5]]])
print_array(arr0)
arr0 = np.array([[1,3,5],[2,4,6],[3,7,11]])
print_array(arr0)




Array: 24, size: 1, itemsize: 4, shape: (), ndim: 0
Array: [1 3 5], size: 3, itemsize: 4, shape: (3,), ndim: 1
Array: [[1]
 [3]
 [5]], size: 3, itemsize: 4, shape: (3, 1), ndim: 2
Array: [[[1]
  [3]
  [5]]], size: 3, itemsize: 4, shape: (1, 3, 1), ndim: 3
Array: [[ 1  3  5]
 [ 2  4  6]
 [ 3  7 11]], size: 9, itemsize: 4, shape: (3, 3), ndim: 2


In [23]:
arr1 = np.array([[1,3,5],[2,4,6],[3,7,11]], dtype=np.int32)
print_array(arr1,1)
arr1 = np.array([[1,3,5],[2,4,6],[3,7,11]], dtype=np.int64)
print_array(arr1,1)
arr1 = np.array([[1,3,5],[2,4,6],[3,7,11]], dtype=np.int16)
print_array(arr1,1)


dtype: int32, size: 9, itemsize: 4, shape: (3, 3), ndim: 2
dtype: int64, size: 9, itemsize: 8, shape: (3, 3), ndim: 2
dtype: int16, size: 9, itemsize: 2, shape: (3, 3), ndim: 2


In [26]:
from itertools import product

def get_pairs(target):
    """
    Generate pairs (x, y) such that x * y == target.
    """
    candidates = range(1, target + 1)
    return list(filter(lambda pair: pair[0] * pair[1] == target, product(candidates, candidates)))


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype=np.int32)
print(arr)
print_array(arr,2)
for pair in get_pairs(arr.size):
    arr = arr.reshape(pair)
    print(f"Reshaped array to {pair}:")
    print(arr)
    print_array(arr,2)
arr = arr.flatten()
print(f"Flattened array:")
print(arr)
print_array(arr,2)

Reshaped array to (1, 12):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
shape: (1, 12), ndim: 2
Reshaped array to (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
shape: (2, 6), ndim: 2
Reshaped array to (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4), ndim: 2
Reshaped array to (4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3), ndim: 2
Reshaped array to (6, 2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
shape: (6, 2), ndim: 2
Reshaped array to (12, 1):
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
shape: (12, 1), ndim: 2
Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,), ndim: 1
